### ISSUE TITLE
Syncing multiple pods with the same settings fails

### ISSUE THREAD

**Issue by hweissig** [sheldonjuncker/node-kubycat#2]
I am trying to sync multiple pods with the following configuration:
```
kubycat:
  namespace: default
  sync:
    - name: multi-sync
      base: /my/base/directory
      from:
        - foo
        - bar
        - manage.py
      to: /code
      pod-label: code.watcher=true
      shell: /bin/sh
```

When kubycat sees any file changes it shows the following output:

```
sync	/my/base/directory/manage.py
 - sync=multi-sync
 - status=Modified
 - kubectl --namespace default get pods -l code.watcher=true -o custom-columns=NAME:metadata.name --no-headers
 - running on all 1 pods
 - kubectl --namespace default cp /my/base/directory/manage.py default/pod1-0 pod2-0:/code/manage.py
  - error:
 ---------------------------------------
 - error: one of src or dest must be a remote file specification
 - /bin/sh: line 1: django-st3-celery-worker-0:/code/manage.py: No such file or directory
 ---------------------------------------
 - exiting with code 127...
 ```
 
Note that it claims to have only found one pod but `kubectl --namespace default get pods -l code.watcher=true -o custom-columns=NAME:metadata.name --no-headers` gives me:

```
pod1-0
pod2-0
```

(All names have been changed to protect the innocent)
