### ISSUE TITLE
Problems with sync-on-start when using build-cache-on-start

### ISSUE THREAD

**Issue by schlichtanders** [sheldonjuncker/node-kubycat#5]
Hello,

I don't know what is going on but want to share this special case which seems not to work as expected
```yaml
# config.yaml
kubycat:
  namespace: my-app-namespace
  sync:
  - name: my-app
    base: /home/myhome/MyApp
    from:
    - src
    - frontend-dist
    - Project.toml
    to: /home/myhome/MyApp
    pod-label: app.kubernetes.io/name=my-app
    shell: /bin/sh
    # Allows Kubycat to send desktop notifications on errors
    notify: true
    # Whether to show the logs for the sync
    show-logs: true
    # Sync files on startup
    sync-on-start: true
    # Build file caches on startup to prevent unintentional syncing
    # build-cache-on-start: true


  - name: MyApp.toml
    base: /home/myhome/MyApp/dev
    from:
    - MyApp.toml
    to: /home/myhome
    pod-label: app.kubernetes.io/name=my-app
    shell: /bin/sh
    # Allows Kubycat to send desktop notifications on errors
    notify: true
    # Whether to show the logs for the sync
    show-logs: true
    # Sync files on startup
    sync-on-start: true
    # Build file caches on startup to prevent unintentional syncing
    # build-cache-on-start: true
```

If I set `build-cache-on-start: true` to true for both, the second part is not synced on start. If I change the MyApp.toml file it will then get synced, but the initial sync does not happen. If I uncomment the build-cache-on-start option as above, everythings works correctly. (Hence this is also my workaround for now).

It would be great if build-cache-on-start works together with sync-on-start.

I hope this information can help
